ALTER TABLE customers
MODIFY first_name VARCHAR(50) NOT NULL,
MODIFY last_name VARCHAR(50) NOT NULL,
MODIFY date_of_birth DATE NOT NULL,
MODIFY email VARCHAR(50) NOT NULL,
MODIFY phone_number VARCHAR(20) NOT NULL;
